name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build and push PHP 5.4
        uses: docker/build-push-action@v1
        with:
          dockerfile: ./Dockerfile-php54
          build_args: PHP_VER=5.4
          tags: 5.4
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: everycity/apache-php

      - name: Build and push PHP 5.6
        uses: docker/build-push-action@v1
        with:
          build_args: PHP_VER=5.6,DEBIAN_VER=stretch
          tags: 5.6
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: everycity/apache-php

      - name: Build and push PHP 7.1
        uses: docker/build-push-action@v1
        with:
          build_args: PHP_VER=7.1
          tags: 7.1
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: everycity/apache-php

      - name: Build and push PHP 7.2
        uses: docker/build-push-action@v1
        with:
          build_args: PHP_VER=7.2
          tags: 7.2
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: everycity/apache-php

      - name: Build and push PHP 7.3
        uses: docker/build-push-action@v1
        with:
          build_args: PHP_VER=7.3
          tags: 7.3
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: everycity/apache-php

      - name: Build and push PHP 7.4
        uses: docker/build-push-action@v1
        with:
          build_args: PHP_VER=7.4
          tags: 7.4,7,latest
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: everycity/apache-php

