name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and push PHP 7.4
        uses: docker/build-push-action@v1
        with:
          build_args: PHP_VER=7.4
          tags: latest,7.4,7
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          registry: registry.hub.docker.com
          repository: everycity/docker-apache-php/docker-apache-php
          tag_with_ref: true
      - name: Build and push PHP 7.3
        uses: docker/build-push-action@v1
        with:
          build_args: PHP_VER=7.3
          tags: 7.3
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          registry: registry.hub.docker.com
          repository: everycity/docker-apache-php/docker-apache-php
          tag_with_ref: true
      - name: Build and push PHP 7.2
        uses: docker/build-push-action@v1
        with:
          build_args: PHP_VER=7.2
          tags: 7.2
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          registry: registry.hub.docker.com
          repository: everycity/docker-apache-php/docker-apache-php
          tag_with_ref: true
